[tool.poetry]
name = "prime_test"
version = "0.1.0"
description = ""
authors = ["ushankax"]

[tool.poetry.dependencies]
python = "^3.6"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
