language: python
python:
        - "3.6"
          dist: xenial
        - "3.7"
          dist: xenial

virtualenv:
  system_site_packages: true

install: make

before_install:
  - pip install poetry

install:
  - make configure

script:
  - make check

script: make lint
