os: osx
language: python
python:
        - "3.6"
        - "3.7"

virtualenv:
  system_site_packages: true

install: make

before_install:
  - pip install poetry

install:
  - make configure

script:
  - make check

script: make lint
